### PR TITLE
Added negative range for double sequential value changes, removed com…

### PR DESCRIPTION
**Pull request by suneetnangia**
## Purpose
* Added negative range sequential node value update for double type.
* Updated integration test to use multi instance plc + removed stale comment.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by algattik** [comment]
LGTM

nit: why is the processing of the negative vs positive ranges different?
    I'd expect that you compute a value in the range zero to (max-min), then add min to it
    this way it's irrelevent whether they're pos or neg

**Comment by suneetnangia** [comment]
Good point, I went that method but could not make it work along with other constraints e.g. also returning upper bound value (inclusively). Something to optimise on for sure, if we can condense the code.

**Comment by buzzfrog** [comment]
LGTM

**Review by peterbryntesson — APPROVED** [review]
LGTM

**Pull request merged**
